export const GET_LATESTS = 'GET_LATESTS';
export const GET_OTHER = 'GET_OTHER';
export const  GET_GALLERY ='GET_GALLERY';
export const GET_SELECTED_NEWS = 'GET_SELECTED_NEWS';
export const CLEAR_SELECTED_NEWS = 'CLEAR_SELECTED_NEWS';
